config:
  corn: 0/30 * * * * ?
  collectCorn: 0 0 0 * * ?
influx:
  db: telegraf
  user: root
  password: root
  url: http://127.0.0.1:8016
zabbix:
  session:
     expire: 10 #单位分钟
bigScreen:
  health:
    cpuPresent: 0.3
    memoryPresent: 0.4
    diskPresent: 0.3
    itemKeyPresent: 0.6
    alarmPresent: 0.4
    cpuHealth: 10
    diskHealth: 50
    memoryHealth: 30
    cpuNoHealth: 90
    diskNoHealth: 90
    memoryNoHealth: 90
spring:
  data:
     mongodb:
        database: alarm
  quartz:
     properties:
        org:
            quartz:
                scheduler:
                    instanceName: clusteredScheduler