feign:
  httpclient:
    enabled: true
thread:
  pool:
    corePoolSize: 3
influx:
  db: telegraf
  user: root
  password: root
  url: http://10.202.229.122:8016
  retentionPolicy: 5
spring:
  kafka:
    consumer:
      bootstrap-servers: 10.202.229.122:9092
      group-id: foo1
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer