alarm:
  default:
    content: 指标应该{method}但是指标{key}当前值为{value}
  statistics:
    corn: 0 0 0/1 * * ? *
sourceAlarm:
  delete:
    day: 15
    corn: 0 0 0 * * ? *
city:
  dicId: 17d00257d372493298d387fd83e49eda
spring:
  data:
    mongodb:
      database: alarm
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      group-id: zabbix_event
      auto-offset-reset: earliest
      enable-auto-commit: true
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: alarmScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_

            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: embedded