feign:
  httpclient:
    enabled: true
thread:
  pool:
    corePoolSize: 3
influx:
  db: telegraf
  user: root
  password: root
  url: http://127.0.0.1:8016
  retentionPolicy: 5
spring:
  kafka:
    consumer:
      group-id: foo1
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: performanceOperaScheduler