spring:
  kafka:
    consumer:
      group-id: cmdb
  data:
    mongodb:
      database: cmdb3
    neo4j:
      uri: bolt://127.0.0.1:7687
      username: neo4j
      password: maxnerva
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: cmdbScheduler
inventory:
  plan:
    prefix: INVEN
  task:
    prefix: INVENT
city:
  dicId: 17d00257d372493298d387fd83e49eda
guacamole:
  username: guacadmin
  password: guacadmin
  ip: 127.0.0.1
  port: 80
  suffix:
  token:
    expire: 30
webssh:
  ip: 10.202.228.8
  port: 8097
account:
  ipCode : managerIp1,ip,managerIp
serviceCostShowPath: http://10.202.229.191:8080/#/staticLink/serviceCost  #服务订单链接的地址