alarm:
  default:
    content: 指标应该{method}但是指标{key}当前值为{value}
  statistics:
    corn: 0 0 0/1 * * ? *
  zabbix:
    count: 5 #zabbix压缩告警采集次数
    cycleCount: 20 #循环最大次数
  threshold:
    startMinute: 5  #阈值压缩quartz在项目启动之后多少分启动
    corn: 0/30 * * * * ? #阈值压缩quartz的频率
    count: 5  #阈值告警采集次数
sourceAlarm:
  delete:
    day: 15
    corn: 0 0 0 * * ? *
city:
  dicId: 17d00257d372493298d387fd83e49eda
spring:
  data:
    mongodb:
      database: alarm
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: alarmScheduler